//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMyMateWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.UserToAddresses = new HashSet<UserToAddress>();
        }
    
        public int id { get; set; }
        public string addressLine { get; set; }
        public string city { get; set; }
        public int provinceId { get; set; }
        public string postalCode { get; set; }
        public Nullable<bool> isPrimary { get; set; }
        public int typeId { get; set; }
        public System.DateTime dtCreated { get; set; }
        public Nullable<System.DateTime> dtUpdated { get; set; }
    
        public virtual AddressType AddressType { get; set; }
        public virtual Province Province { get; set; }
        public virtual ICollection<UserToAddress> UserToAddresses { get; set; }
    }
}
