//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMyMateWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public File()
        {
            this.MessageToFiles = new HashSet<MessageToFile>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string path { get; set; }
        public int infoId { get; set; }
        public int appId { get; set; }
        public int userId { get; set; }
        public System.DateTime dtCreated { get; set; }
        public Nullable<System.DateTime> dtUpdated { get; set; }
        public Nullable<System.DateTime> dtDeleted { get; set; }
    
        public virtual FileApp FileApp { get; set; }
        public virtual FileInfo FileInfo { get; set; }
        public virtual ICollection<MessageToFile> MessageToFiles { get; set; }
    }
}
