//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMyMateWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localization
    {
        public int id { get; set; }
        public int languageId { get; set; }
        public string refCode { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int tableId { get; set; }
        public System.DateTime dtCreated { get; set; }
        public Nullable<System.DateTime> dtUpdated { get; set; }
        public Nullable<System.DateTime> dtDeleted { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Table Table { get; set; }
    }
}
