//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMyMateWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.MenuToMenuItems = new HashSet<MenuToMenuItem>();
            this.SectionToMenus = new HashSet<SectionToMenu>();
        }
    
        public int id { get; set; }
        public string refCode { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int objectId { get; set; }
        public int order { get; set; }
        public int contextId { get; set; }
        public System.DateTime dtCreated { get; set; }
        public Nullable<System.DateTime> dtUpdated { get; set; }
        public Nullable<System.DateTime> dtDeleted { get; set; }
    
        public virtual ObjectContext ObjectContext { get; set; }
        public virtual Object Object { get; set; }
        public virtual ICollection<MenuToMenuItem> MenuToMenuItems { get; set; }
        public virtual ICollection<SectionToMenu> SectionToMenus { get; set; }
    }
}
