//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMyMateWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public MenuItem()
        {
            this.MenuItem1 = new HashSet<MenuItem>();
            this.MenuToMenuItems = new HashSet<MenuToMenuItem>();
        }
    
        public int id { get; set; }
        public string refCode { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> parentId { get; set; }
        public int objectId { get; set; }
        public int order { get; set; }
        public int contextId { get; set; }
        public string icon { get; set; }
        public string link { get; set; }
        public Nullable<bool> isActive { get; set; }
        public System.DateTime dtCreated { get; set; }
        public Nullable<System.DateTime> dtUpdated { get; set; }
        public Nullable<System.DateTime> dtDeleted { get; set; }
    
        public virtual ObjectContext ObjectContext { get; set; }
        public virtual ICollection<MenuItem> MenuItem1 { get; set; }
        public virtual MenuItem MenuItem2 { get; set; }
        public virtual Object Object { get; set; }
        public virtual ICollection<MenuToMenuItem> MenuToMenuItems { get; set; }
    }
}
