//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMyMateWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.Message1 = new HashSet<Message>();
            this.MessageToFiles = new HashSet<MessageToFile>();
            this.UserToMessages = new HashSet<UserToMessage>();
        }
    
        public int id { get; set; }
        public Nullable<int> parentId { get; set; }
        public int authorId { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public System.Guid guid { get; set; }
        public System.DateTime dtCreated { get; set; }
        public Nullable<System.DateTime> dtUpdated { get; set; }
        public Nullable<System.DateTime> dtDeleted { get; set; }
    
        public virtual ICollection<Message> Message1 { get; set; }
        public virtual Message Message2 { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<MessageToFile> MessageToFiles { get; set; }
        public virtual ICollection<UserToMessage> UserToMessages { get; set; }
    }
}
