//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMyMateWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectRight
    {
        public ObjectRight()
        {
            this.RoleGroupObjectRights = new HashSet<RoleGroupObjectRight>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string dtCreated { get; set; }
        public string dtUpdated { get; set; }
    
        public virtual ICollection<RoleGroupObjectRight> RoleGroupObjectRights { get; set; }
    }
}
