//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMyMateWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        public Object()
        {
            this.Menus = new HashSet<Menu>();
            this.MenuItems = new HashSet<MenuItem>();
            this.Sections = new HashSet<Section>();
            this.GroupObjects = new HashSet<GroupObject>();
            this.ObjectGroupObjects = new HashSet<ObjectGroupObject>();
            this.SettingAnswers = new HashSet<SettingAnswer>();
            this.SettingAreas = new HashSet<SettingArea>();
            this.ProfileAnswers = new HashSet<ProfileAnswer>();
            this.ProfileAreas = new HashSet<ProfileArea>();
            this.ProfileQuestionnaires = new HashSet<ProfileQuestionnaire>();
            this.RoleGroupObjectRights = new HashSet<RoleGroupObjectRight>();
            this.SettingQuestionnaires = new HashSet<SettingQuestionnaire>();
        }
    
        public int id { get; set; }
        public int tableId { get; set; }
        public System.DateTime dtCreated { get; set; }
        public Nullable<System.DateTime> dtUpdated { get; set; }
        public Nullable<System.DateTime> dtDeleted { get; set; }
    
        public virtual ICollection<Menu> Menus { get; set; }
        public virtual ICollection<MenuItem> MenuItems { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
        public virtual Table Table { get; set; }
        public virtual ICollection<GroupObject> GroupObjects { get; set; }
        public virtual ICollection<ObjectGroupObject> ObjectGroupObjects { get; set; }
        public virtual ICollection<SettingAnswer> SettingAnswers { get; set; }
        public virtual ICollection<SettingArea> SettingAreas { get; set; }
        public virtual ICollection<ProfileAnswer> ProfileAnswers { get; set; }
        public virtual ICollection<ProfileArea> ProfileAreas { get; set; }
        public virtual ICollection<ProfileQuestionnaire> ProfileQuestionnaires { get; set; }
        public virtual ICollection<RoleGroupObjectRight> RoleGroupObjectRights { get; set; }
        public virtual ICollection<SettingQuestionnaire> SettingQuestionnaires { get; set; }
    }
}
