//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMyMateWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public Phone()
        {
            this.UserToPhones = new HashSet<UserToPhone>();
        }
    
        public int id { get; set; }
        public string prefix { get; set; }
        public string number { get; set; }
        public Nullable<int> typeId { get; set; }
        public Nullable<bool> isPrimary { get; set; }
        public System.DateTime dtCreated { get; set; }
        public Nullable<System.DateTime> dtUpdated { get; set; }
        public Nullable<System.DateTime> dtDeleted { get; set; }
    
        public virtual PhoneType PhoneType { get; set; }
        public virtual ICollection<UserToPhone> UserToPhones { get; set; }
    }
}
