//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMyMateWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileAnswer
    {
        public ProfileAnswer()
        {
            this.ProfileQuestionnaireToAnswers = new HashSet<ProfileQuestionnaireToAnswer>();
            this.UserProfileInfoes = new HashSet<UserProfileInfo>();
        }
    
        public int id { get; set; }
        public string refCode { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int objectId { get; set; }
        public int contextId { get; set; }
        public bool isDefault { get; set; }
        public System.DateTime dtCreated { get; set; }
        public Nullable<System.DateTime> dtUpdated { get; set; }
        public Nullable<System.DateTime> dtDeleted { get; set; }
        public int value { get; set; }
    
        public virtual Object Object { get; set; }
        public virtual ICollection<ProfileQuestionnaireToAnswer> ProfileQuestionnaireToAnswers { get; set; }
        public virtual ICollection<UserProfileInfo> UserProfileInfoes { get; set; }
    }
}
