//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMyMateWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.GroupToRoles = new HashSet<GroupToRole>();
            this.RoleGroupObjectRights = new HashSet<RoleGroupObjectRight>();
            this.RoleToUsers = new HashSet<RoleToUser>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool isPrimary { get; set; }
        public System.DateTime dtCreated { get; set; }
        public Nullable<System.DateTime> dtUpdated { get; set; }
    
        public virtual ICollection<GroupToRole> GroupToRoles { get; set; }
        public virtual ICollection<RoleGroupObjectRight> RoleGroupObjectRights { get; set; }
        public virtual ICollection<RoleToUser> RoleToUsers { get; set; }
    }
}
