//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMyMateWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public Table()
        {
            this.Localizations = new HashSet<Localization>();
            this.Objects = new HashSet<Object>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int objectId { get; set; }
        public System.DateTime dtCreated { get; set; }
        public Nullable<System.DateTime> dtUpdated { get; set; }
    
        public virtual ICollection<Localization> Localizations { get; set; }
        public virtual ICollection<Object> Objects { get; set; }
    }
}
