//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMyMateWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.RoleToUsers = new HashSet<RoleToUser>();
            this.Messages = new HashSet<Message>();
            this.Notifications = new HashSet<Notification>();
            this.Reviews = new HashSet<Review>();
            this.Reviews1 = new HashSet<Review>();
            this.UserProfileInfoes = new HashSet<UserProfileInfo>();
            this.UserSettingInfoes = new HashSet<UserSettingInfo>();
            this.UserToAddresses = new HashSet<UserToAddress>();
            this.UserToJobs = new HashSet<UserToJob>();
            this.UserToFriends = new HashSet<UserToFriend>();
            this.UserToFriends1 = new HashSet<UserToFriend>();
            this.UserToLanguages = new HashSet<UserToLanguage>();
            this.UserToMessages = new HashSet<UserToMessage>();
            this.UserToNationalities = new HashSet<UserToNationality>();
            this.UserToNotifications = new HashSet<UserToNotification>();
            this.UserToPhones = new HashSet<UserToPhone>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string name { get; set; }
        public string middleName { get; set; }
        public string surname { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public System.Guid guid { get; set; }
        public int genderId { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public int avatarId { get; set; }
        public int statusId { get; set; }
        public int registrationStatusId { get; set; }
        public string description { get; set; }
        public System.DateTime dtCreated { get; set; }
        public Nullable<System.DateTime> dtUpdated { get; set; }
        public Nullable<System.DateTime> dtDeleted { get; set; }
    
        public virtual ICollection<RoleToUser> RoleToUsers { get; set; }
        public virtual Avatar Avatar { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<Review> Reviews1 { get; set; }
        public virtual UserRegistrationStatu UserRegistrationStatu { get; set; }
        public virtual UserStatu UserStatu { get; set; }
        public virtual UserLog UserLog { get; set; }
        public virtual ICollection<UserProfileInfo> UserProfileInfoes { get; set; }
        public virtual ICollection<UserSettingInfo> UserSettingInfoes { get; set; }
        public virtual ICollection<UserToAddress> UserToAddresses { get; set; }
        public virtual ICollection<UserToJob> UserToJobs { get; set; }
        public virtual ICollection<UserToFriend> UserToFriends { get; set; }
        public virtual ICollection<UserToFriend> UserToFriends1 { get; set; }
        public virtual ICollection<UserToLanguage> UserToLanguages { get; set; }
        public virtual ICollection<UserToMessage> UserToMessages { get; set; }
        public virtual ICollection<UserToNationality> UserToNationalities { get; set; }
        public virtual ICollection<UserToNotification> UserToNotifications { get; set; }
        public virtual ICollection<UserToPhone> UserToPhones { get; set; }
    }
}
