//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMyMateWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserToFriend
    {
        public int userId { get; set; }
        public int friendId { get; set; }
        public int statusId { get; set; }
        public int objectId { get; set; }
        public System.DateTime dtCreated { get; set; }
        public Nullable<System.DateTime> dtUpdated { get; set; }
        public Nullable<System.DateTime> dtDeleted { get; set; }
    
        public virtual FriendshipStatu FriendshipStatu { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
