//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMyMateWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int userId { get; set; }
        public Nullable<System.DateTime> activationDate { get; set; }
        public Nullable<System.DateTime> lastRecoveringDate { get; set; }
        public Nullable<System.DateTime> lastLoginDate { get; set; }
        public Nullable<System.DateTime> lastLogoutDate { get; set; }
        public Nullable<System.DateTime> dtCreated { get; set; }
    
        public virtual User User { get; set; }
    }
}
