//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeMyMateWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfileInfo
    {
        public int userId { get; set; }
        public int questionnaireId { get; set; }
        public int answerId { get; set; }
        public System.DateTime dtCreated { get; set; }
        public Nullable<System.DateTime> dtUpdated { get; set; }
        public Nullable<System.DateTime> dtDeleted { get; set; }
    
        public virtual ProfileAnswer ProfileAnswer { get; set; }
        public virtual ProfileQuestionnaire ProfileQuestionnaire { get; set; }
        public virtual User User { get; set; }
    }
}
