CREATE TRIGGER [SettingAreaDel]
	ON [User].[SettingArea]
	INSTEAD OF DELETE
	AS
	BEGIN
		SET NOCOUNT ON
		
		UPDATE [User].[SettingArea]
		SET dtDeleted = GETDATE()
		WHERE id IN (SELECT DISTINCT id FROM DELETED)
	END
