CREATE TRIGGER [UserToPhoneDel]
	ON [User].[UserToPhone]
	INSTEAD OF DELETE
	AS
	BEGIN
		SET NOCOUNT ON

		UPDATE [User].[UserToPhone]
		SET dtDeleted = GETDATE() 
		WHERE 
		userId IN (SELECT DISTINCT userId FROM DELETED) and 
		phoneId IN (SELECT DISTINCT phoneId FROM DELETED);
	END
